# Generated by Django 6.0.2 on 2026-02-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('ERROR', 'Erro'), ('WARNING', 'Aviso')], default='INFO', max_length=10)),
                ('acao', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=150)),
                ('detalhes', models.TextField(blank=True, default='')),
                ('empresa', models.CharField(blank=True, default='', max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_logsis_timesta_185863_idx'), models.Index(fields=['usuario'], name='core_logsis_usuario_6ac82e_idx'), models.Index(fields=['empresa'], name='core_logsis_empresa_4d3279_idx'), models.Index(fields=['nivel'], name='core_logsis_nivel_6983e7_idx')],
            },
        ),
    ]
