# Generated by Django 5.1.5 on 2026-02-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='escala',
            new_name='operacao_es_data_in_a0457d_idx',
            old_name='operacao_escala_dt_emp_idx',
        ),
    ]
